services:
  db:
    image: mariadb:10.6.13
    container_name: mariadb_prd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - target: 3306
        published: 3306
    volumes:
      - /opt/mariadb_data/data/:/var/lib/mysql
    networks:
      - mariadb_network

networks:
  mariadb_network:
    driver: bridge

volumes:
  db_data:
